apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wedding
  name: wedding-registration-admin-deployment
  labels:
    app: wedding-registration-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wedding-registration-admin
  template:
    metadata:
      labels:
        app: wedding-registration-admin
    spec:
      containers:
        - name: wedding-registration-admin
          image: ghcr.io/lucascarioca/wedding-registration-admin-homelab:latest
          ports:
            - containerPort: 80
              name: w-r-a-http
---
apiVersion: v1
kind: Service
metadata:
  namespace: wedding
  name: wedding-registration-admin
spec:
  type: NodePort
  ports:
    - name: tcp
      port: 80
      nodePort: 30004
      targetPort: w-r-a-http
  selector:
    app: wedding-registration-admin
