name: Promote -> DO
on:
  workflow_dispatch:
jobs:
  release:
    if: github.ref == 'refs/heads/main'
    uses: LucasCarioca/workflows/.github/workflows/release-do-yarn.yml@v0.5.1
    with:
      registry: ghcr.io
      image_name: lucascarioca/wedding-registration-admin
      deployment: wedding-admin
      container: wedding-admin
      namespace: wedding
    secrets:
      kube_config: ${{ secrets.DO_KUBE_CONFIG }}
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}